version: '3'
services:
  pacs_data_migration_tool:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    volumes: 
      - ./bin:/app
    working_dir: /app
    command: dotnet PacsDataMigrationTool.dll